#!/usr/bin/env python3
import json
import os
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]  # Go up to project root
JSON_PATH = ROOT / "data" / "input-data.json"

# Get template name from command-line argument
if len(sys.argv) < 2:
    print("Usage: python3 generate_config.py <template_name>", file=sys.stderr)
    sys.exit(1)

TEMPLATE_NAME = sys.argv[1]
TEMPLATE_DIR = ROOT / "templates" / TEMPLATE_NAME
OUT_PATH = TEMPLATE_DIR / "template" / "_config.tex"
SECTIONS_DIR = TEMPLATE_DIR / "template" / "sections"


def tex_escape(s: str) -> str:
    # Minimal escaping for LaTeX macro values.
    # Preserves LaTeX commands like \textbf{}, \textit{}, etc.
    # We intentionally keep it conservative (resume content often needs raw LaTeX).
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = []
    i = 0
    while i < len(s):
        # Check if this is a LaTeX command
        if s[i] == "\\" and i + 1 < len(s):
            # Find the end of the command and its arguments
            j = i + 1
            while j < len(s) and s[j].isalpha():
                j += 1
            # Check if there are curly braces following
            if j < len(s) and s[j] == "{":
                # Find matching closing brace
                brace_count = 1
                k = j + 1
                while k < len(s) and brace_count > 0:
                    if s[k] == "{":
                        brace_count += 1
                    elif s[k] == "}":
                        brace_count -= 1
                    k += 1
                # Keep the entire LaTeX command with arguments as-is
                out.append(s[i:k])
                i = k
            else:
                # Just the command without arguments
                out.append(s[i:j])
                i = j
        else:
            ch = s[i]
            out.append(replacements.get(ch, ch))
            i += 1
    return "".join(out)


def get(data, key, default=""):
    v = data.get(key, default)
    if v is None:
        return default
    return str(v)


def generate_config(data: dict) -> str:
    """Generate _config.tex with header information."""
    mapping = {
        "name": ("name", False),
        "phone": ("phone", False),
        "city": ("city", False),
        "email": ("email", False),
        "linkedin": ("LinkedIn", False),
        "github": ("github", False),
        "role": ("role", False),
        "portfolioUrl": ("portfoliourl", False),
        "portfolioName": ("portfolioname", False),
    }

    lines = []
    lines.append("% Auto-generated. Edit resume.json, then rebuild.")
    lines.append("% Generated by scripts/generate_config.py")
    lines.append("")
    for json_key, (tex_macro, allow_raw) in mapping.items():
        raw = get(data, json_key, "")
        val = raw if allow_raw else tex_escape(raw)
        lines.append(rf"\def\{tex_macro}{{{val}}}")
    lines.append("")
    return "\n".join(lines)


def generate_objective(data: dict) -> str:
    """Generate sections/objective.tex from JSON."""
    lines = []
    lines.append("%====================")
    lines.append("% Objective Statement")
    lines.append("%====================")
    lines.append("")
    lines.append("")
    objective = get(data, "objective", "")
    if objective:
        lines.append(tex_escape(objective))
    lines.append("")
    return "\n".join(lines)


def generate_skills(data: dict) -> str:
    """Generate sections/skills.tex from JSON."""
    skills = data.get("skills", [])
    if not skills:
        return ""
    
    lines = []
    lines.append(r"\begin{tabular}{p{11em} p{1em} p{43em}}")
    
    for skill in skills:
        category = tex_escape(skill.get("category", ""))
        items = tex_escape(skill.get("items", ""))
        lines.append(rf"\skills{{{category}}} & &    {items} \\")
    
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


def generate_experience(data: dict) -> str:
    """Generate sections/experience.tex from JSON."""
    experiences = data.get("experience", [])
    lines = []
    
    for i, exp in enumerate(experiences):
        if i > 0:
            lines.append("")
        lines.append("%====================")
        lines.append(f"% EXPERIENCE {chr(65 + i)}")
        lines.append("%====================")
        
        role = tex_escape(exp.get("role", "")).upper()
        start = exp.get("startDate", "")
        end = exp.get("endDate", "")
        company = tex_escape(exp.get("company", ""))
        description = exp.get("description", "")
        
        date_colored = rf"\color{{highlight}} {start} --- {end}"
        lines.append(rf"\subsection{{{role} \hfill {date_colored}}}")
        
        company_colored = rf"\color{{highlight}} {company}"
        lines.append(rf"\subtext{{{company_colored}}}\vspace{{0.6em}}")
        
        if description:
            lines.append(tex_escape(description))
        
        lines.append(r"\begin{zitemize}")
        
        for highlight in exp.get("highlights", []):
            lines.append(rf"    \item {tex_escape(highlight)}")
        
        lines.append(r"\end{zitemize}")
        
        # Add spacing after each experience except the last one
        if i < len(experiences) - 1:
            lines.append(r"\vspace{0.3em}")
    
    return "\n".join(lines)


def generate_education(data: dict) -> str:
    """Generate sections/education.tex from JSON."""
    education = data.get("education", [])
    lines = []
    
    for edu in education:
        degree = tex_escape(edu.get("degree", ""))
        institution = tex_escape(edu.get("institution", ""))
        date = edu.get("date", "")
        lines.append(rf"\skills{{{degree}}}, \textit{{{institution}}}	\hfill {{\color{{highlight}} {date}}}")
        lines.append("")
    
    return "\n".join(lines)


def generate_awards(data: dict) -> str:
    """Generate sections/awards.tex from JSON."""
    awards = data.get("awards", [])
    lines = []
    
    if awards:
        lines.append(r"\begin{zitemize}")
        for award in awards:
            title = tex_escape(award.get("title", ""))
            institution = tex_escape(award.get("institution", ""))
            date = award.get("date", "")
            lines.append(rf"\item \skills{{{title}}}, \textit{{{institution}}} \hfill {{\color{{highlight}} {date}}}")
        lines.append(r"\end{zitemize}")
    
    return "\n".join(lines)


def generate_activities(data: dict) -> str:
    """Generate sections/activities.tex from JSON."""
    activities = data.get("activities", [])
    lines = []
    
    for activity in activities:
        lines.append(f"\\item {tex_escape(activity)}")
    
    if lines:
        lines.insert(0, r"\begin{itemize}")
        lines.append(r"\end{itemize}")
    
    return "\n".join(lines)


def main() -> int:
    if not JSON_PATH.exists():
        print(f"Missing {JSON_PATH}", file=sys.stderr)
        return 1

    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    # Generate _config.tex
    OUT_PATH.write_text(generate_config(data), encoding="utf-8")
    
    # Generate section files
    (SECTIONS_DIR / "objective.tex").write_text(generate_objective(data), encoding="utf-8")
    (SECTIONS_DIR / "skills.tex").write_text(generate_skills(data), encoding="utf-8")
    (SECTIONS_DIR / "experience.tex").write_text(generate_experience(data), encoding="utf-8")
    (SECTIONS_DIR / "activities.tex").write_text(generate_activities(data), encoding="utf-8")
    (SECTIONS_DIR / "awards.tex").write_text(generate_awards(data), encoding="utf-8")
    (SECTIONS_DIR / "education.tex").write_text(generate_education(data), encoding="utf-8")
    
    print("Generated all resume sections from resume.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
